name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
      - automated_deployment
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set timestamp tag
        id: vars
        run: echo "timestamp=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ env.timestamp }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set SSH private key
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ vars.SSH_HOST }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts

      - name: Create remote directory
        run: |
          ssh -i ~/.ssh/id_ed25519 root@${{ vars.SSH_HOST }} <<'EOF'
            set -euo pipefail
            mkdir -p /docker/agynamix
            chmod 0755 /docker/agynamix
          EOF

      - name: Copy docker-compose file
        run: |
          scp -i ~/.ssh/id_ed25519 ./docker-compose.yml root@${{ vars.SSH_HOST }}:/docker/agynamix/docker-compose.yml

      - name: Start Docker container
        run: |
          ssh -i ~/.ssh/id_ed25519 root@${{ vars.SSH_HOST }} <<'EOF'
            set -euo pipefail
            cd /docker/agynamix
            docker-compose pull
            docker-compose up -d --force-recreate --remove-orphans
          EOF
