name: Build and Deploy Docker Image

on:
  push:
    branches:
      - automated_deployment
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set timestamp tag
        id: vars
        run: echo "timestamp=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ env.timestamp }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH and deploy
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.SSH_HOST }} <<'EOF'
            set -e
            mkdir -p /docker/agynamix
            chmod 0755 /docker/agynamix
            exit
          EOF

      - name: Copy docker-compose file
        run: |
          scp -o StrictHostKeyChecking=no ./docker-compose.yml root@${{ secrets.SSH_HOST }}:/docker/agynamix/docker-compose.yml

      - name: Start Docker container
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.SSH_HOST }} <<'EOF'
            cd /docker/agynamix
            docker-compose pull
            docker-compose up -d
          EOF
